language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install: 
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

