[versions]
androidx_app_compat = "1.0.2"
androidx_recycler_view = "1.1.0"
androidx_test_espresso = "3.3.0-alpha02"
androidx_test_ext_junit = "1.1.2-alpha02"
androidx_test_orchestrator = "1.1.0"
androidx_test_rules = "1.1.0"
androidx_test_runner = "1.1.0"
constraint_layout = "2.0.4"
google_exoplayer = "r1.5.15"
google_guava = "27.1-android"
irradia_fieldrush = "0.0.16"
irradia_mime = "1.1.1"
jackson = "2.10.2"
jcip = "1.0.2"
joda_time = "2.10.5"
junit = "4.12"
kotlin = "1.4.20"
logback_android = "2.0.0"
logback_classic = "1.3.0-alpha5"
mockito = "2.27.0"
nimbus_jose_jwt = "8.20"
okhttp = "3.14.1"
quicktheories = "0.26"
rxjava = "1.3.8"
slf4j = "2.0.0-alpha1"

[libraries]
androidx_app_compat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_app_compat" }
androidx_recycler_view = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx_recycler_view" }
androidx_test_espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx_test_espresso" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx_test_ext_junit" }
androidx_test_orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx_test_orchestrator" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test_rules" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test_runner" }
constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint_layout" }
google_exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "google_exoplayer" }
google_guava = { module = "com.google.guava:guava", version.ref = "google_guava" }
irradia_fieldrush_api = { module = "one.irradia.fieldrush:one.irradia.fieldrush.api", version.ref = "irradia_fieldrush" }
irradia_fieldrush_vanilla = { module = "one.irradia.fieldrush:one.irradia.fieldrush.vanilla", version.ref = "irradia_fieldrush" }
irradia_mime_api = { module = "one.irradia.mime:one.irradia.mime.api", version.ref = "irradia_mime" }
irradia_mime_vanilla = { module = "one.irradia.mime:one.irradia.mime.vanilla", version.ref = "irradia_mime" }
jackson_core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson_databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jcip = { module = "com.io7m.jcip:jcip-annotations", version.ref = "jcip" }
joda_time = { module = "joda-time:joda-time", version.ref = "joda_time" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
logback_android = { module = "com.github.tony19:logback-android", version.ref = "logback_android" }
logback_classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback_classic" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
nimbus_jose_jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus_jose_jwt" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
quicktheories = { module = "org.quicktheories:quicktheories", version.ref = "quicktheories" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
